spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.10.16.140:3306/goldencis_vdp?generateSimpleParameterMetadata=true&amp;characterEncoding=UTF-8
    username: root
    password: K20zOdcrZJkPwGshpOr3+j6LRz/7whhf16HfBBk2oYZ2LVibVjp02QACoiduUcbb27zuscMgCqhjDIS8eUmVFw==
server:
  port: 80
  servlet:
    context-path: /tdp
