spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/goldencis_tdp?generateSimpleParameterMetadata=true&amp;characterEncoding=UTF-8
    username: root
    password: goldencis
server:
  port: 80
  servlet:
    context-path: /tdp
