spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/goldencis_tdp?generateSimpleParameterMetadata=true&amp;characterEncoding=UTF-8
    username: root
    password: goldencis
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
  output:
    ansi:
      enabled: detect
  cache:
    caffeine:
      spec: initialCapacity=100,maximumSize=1000,expireAfterAccess=600s,

server:
  port: 80
  servlet:
    context-path: /tdp

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml

guava:
  cacheSize: 10000
  timeLength: 1000
